//go:build darwin

// config + autostart subcommands: generates a monctl.app wrapper and a
// LaunchAgent that opens it. Rationale: on modern macOS, TCC binds
// Accessibility grants of bare ad-hoc executables to the exact code hash and
// does not reliably honor them for launchd-spawned processes; app bundles
// are keyed by bundle identity (the supported path — same approach as the
// yabai/skhd service bundles). The wrapper script spawns `monctl watch` in
// a restart loop (launchd KeepAlive equivalent). Grant Accessibility to
// monctl.app once; it survives binary rebuilds.
package main

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const launchAgentLabel = "com.bacnh85.monctl"

// registerHint is appended to hotkey registration errors by watch.go.
const registerHint = "(grant Accessibility: System Settings -> Privacy & Security -> Accessibility)"

// wrapperScript is the bundle's restart loop. It execs the IN-BUNDLE
// binary (bundle TCC attribution), with backoff while untrusted: 3 fast
// retries, then 60s slow-poll (bounded log growth).
func wrapperScript(binPath string) string {
	return fmt.Sprintf(`#!/bin/sh
# monctl.app wrapper - generated by monctl autostart
BIN=%q
# ponytail: debug-on in the field log; drop if the log gets noisy
export MONCTL_DEBUG=1
retries=0
while true; do
	"$BIN" watch >> /tmp/monctl-watch.log 2>&1
	rc=$?
	if [ $rc -eq 0 ]; then
		retries=0
		sleep 2			# clean exit: restart promptly
	elif [ $retries -lt 3 ]; then
		retries=$((retries+1))
		sleep 2			# quick retry a few times (e.g. panic)
	else
		echo "$(date) monctl watch rc=$rc - still failing; retrying in 60s" >> /tmp/monctl-watch.log
		sleep 60		# untrusted / config broken: back off
	fi
done
`, binPath)
}

const wrapperInfoPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>monctl</string>
	<key>CFBundleIdentifier</key>
	<string>com.bacnh85.monctl</string>
	<key>CFBundleName</key>
	<string>monctl</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>LSUIElement</key>
	<true/>
</dict>
</plist>
`

// ensureWrapperApp creates/refreshes ~/Applications/monctl.app and copies
// the monctl binary INTO the bundle. TCC attributes the event-tap request to
// the bundle only when the requesting executable lives inside it — spawning
// a bare binary (e.g. ~/bin/monctl) is hash-keyed separately and never
// matches the bundle grant (verified live: rc=1 despite bundle granted).
// Also builds/installs the osd helper (native brightness overlay) next to
// the binary when swiftc is available.
func ensureWrapperApp() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	src, err := os.Executable()
	if err != nil {
		return "", err
	}
	if resolved, err := filepath.EvalSymlinks(src); err == nil {
		src = resolved
	}
	// Already running from inside an installed .app (e.g. /Applications/
	// monctl.app from the DMG): use THAT bundle — never duplicate it.
	if i := strings.Index(src, ".app/Contents/MacOS/"); i >= 0 {
		app := src[:i+4]
		if err := writeWrapper(app, src); err != nil {
			return "", err
		}
		return app, nil
	}
	app := filepath.Join(home, "Applications", "monctl.app")
	inner := filepath.Join(app, "Contents", "MacOS", "monctl")
	if err := os.MkdirAll(filepath.Dir(inner), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(app, "Contents", "Info.plist"), []byte(wrapperInfoPlist), 0o644); err != nil {
		return "", err
	}
	// Only copy when the binary actually changed: rewriting the file breaks
	// the bundle seal (forcing a re-sign, which voids the TCC grant).
	if src != inner && !filesIdentical(src, inner) {
		if err := copyFile(src, inner); err != nil {
			return "", err
		}
	}
	// Wrapper restarts the in-bundle binary (KeepAlive semantics; the agent
	// runs the wrapper directly, no `open`/LaunchServices in the chain).
	if err := writeWrapper(app, inner); err != nil {
		return "", err
	}
	// Build the OSD helper into the bundle (best effort — needs swiftc; the
	// daemon degrades silently to no-OSD when it's absent). Rebuild only when
	// the source is newer than the installed binary.
	if _, err := os.Stat("/usr/bin/swiftc"); err == nil {
		if src, err := findOSDSource(); err == nil {
			osdBin := filepath.Join(filepath.Dir(inner), "osd")
			si, err1 := os.Stat(src)
			bi, err2 := os.Stat(osdBin)
			if err1 == nil && (err2 != nil || si.ModTime().After(bi.ModTime())) {
				_ = exec.Command("/usr/bin/swiftc", "-O", src, "-o", osdBin).Run()
			}
		}
	}
	// Ad-hoc sign so TCC sees a stable bundle identity — but only when the
	// signature is missing/invalid: ad-hoc apps are pinned by their signature
	// hash, so re-signing on every run would invalidate the user's grant.
	if err := exec.Command("codesign", "--verify", "--deep", app).Run(); err != nil {
		_ = exec.Command("codesign", "--force", "--deep", "-s", "-", app).Run()
	}
	return app, nil
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o755)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

// findOSDSource locates tools/osd/main.swift (repo checkout) — dev-time
// convenience; without it autostart simply skips the OSD helper.
func findOSDSource() (string, error) {
	for _, dir := range []string{
		"/Volumes/Dev/homelab/monctl", // ponytail: repo path pin; derive from debug.ReadFirstFrame if this ever ships outside homelab
	} {
		cand := filepath.Join(dir, "tools", "osd", "main.swift")
		if _, err := os.Stat(cand); err == nil {
			return cand, nil
		}
	}
	return "", os.ErrNotExist
}

// filesIdentical compares size + sha256 cheaply enough for a binary.
func filesIdentical(a, b string) bool {
	fa, err1 := os.Stat(a)
	fb, err2 := os.Stat(b)
	if err1 != nil || err2 != nil || !fa.Mode().IsRegular() || !fb.Mode().IsRegular() || fa.Size() != fb.Size() {
		return false
	}
	ha, err1 := sha256File(a)
	hb, err2 := sha256File(b)
	return err1 == nil && err2 == nil && ha == hb
}

func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", h.Sum(nil)), nil
}

// writeWrapper installs the restart-loop script next to the inner binary
// and re-signs the bundle only when the seal is actually broken.
func writeWrapper(app, inner string) error {
	if err := os.WriteFile(filepath.Join(filepath.Dir(inner), "monctl-wrapper"), []byte(wrapperScript(inner)), 0o755); err != nil {
		return err
	}
	if err := exec.Command("codesign", "--verify", "--deep", app).Run(); err != nil {
		_ = exec.Command("codesign", "--force", "--deep", "-s", "-", app).Run()
	}
	return nil
}

func cmdAutostart(argv []string) int {
	remove := false
	fs := flag.NewFlagSet("autostart", flag.ContinueOnError)
	fs.BoolVar(&remove, "remove", false, "remove autostart entry")
	if err := fs.Parse(argv); err != nil {
		return 2
	}
	uid := fmt.Sprint(os.Getuid())
	home, err := os.UserHomeDir()
	if err != nil {
		return fail(err)
	}
	plist := filepath.Join(home, "Library", "LaunchAgents", launchAgentLabel+".plist")
	if remove {
		_ = exec.Command("launchctl", "bootout", "gui/"+uid+"/"+launchAgentLabel).Run()
		if err := os.Remove(plist); err != nil {
			return fail(err)
		}
		fmt.Println("autostart removed:", plist)
		return 0
	}
	app, err := ensureWrapperApp()
	if err != nil {
		return fail(err)
	}
	wrapperPath := filepath.Join(app, "Contents", "MacOS", "monctl-wrapper")
	content := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>%s</string>
	<key>ProgramArguments</key>
	<array>
		<string>%s</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>ThrottleInterval</key>
	<integer>30</integer>
</dict>
</plist>
`, launchAgentLabel, wrapperPath)
	if err := os.MkdirAll(filepath.Dir(plist), 0o755); err != nil {
		return fail(err)
	}
	if err := os.WriteFile(plist, []byte(content), 0o644); err != nil {
		return fail(err)
	}
	if err := exec.Command("launchctl", "bootstrap", "gui/"+uid, plist).Run(); err != nil {
		_ = exec.Command("launchctl", "load", plist).Run()
	}
	fmt.Printf("autostart registered: %s (opens %s)\n", plist, app)
	fmt.Println("If hotkeys do not work, grant Accessibility to monctl:")
	fmt.Println("  System Settings -> Privacy & Security -> Accessibility -> + -> Cmd+Shift+G ->", app)
	return 0
}
